describe('template spec', () => {
  it('Registration', () => {
    cy.visit('https://dabrostyle.com/')
    cy.get('.svg-profile').click()
    cy.wait(2000)
    cy.get(':nth-child(2) > .ec-link').click()
    cy.wait(2000)
    cy.get('#ec-register-name-input').type("Test")
    cy.wait(2000)
    cy.get('#ec-register-email-input').type("test@mail.ru")
    cy.wait(2000)
    cy.get('#ec-register-password-input').type("test1337")
    cy.wait(2000)
    cy.get('.svg-icon').click()
  })
  it('Registration_ERROR', () => {
    cy.visit('https://dabrostyle.com/')
    cy.get('.svg-profile').click()
    cy.wait(2000)
    cy.get(':nth-child(2) > .ec-link').click()
    cy.wait(2000)
    cy.get('#ec-register-name-input').type("Test")
    cy.wait(2000)
    cy.get('#ec-register-email-input').type("test")
    cy.wait(2000)
    cy.get('#ec-register-password-input').type("test")
    cy.wait(2000)
    cy.get('.svg-icon').click()
  })
  it('Auth', () => {
    cy.visit('https://dabrostyle.com/')
    cy.get('.svg-profile').click()
    cy.wait(2000)
    cy.get('#ec-login-email-input').type('Tester@mail.ru')
    cy.wait(2000)
    cy.get('#ec-login-password-input').type('Test1337')
    cy.wait(2000)
    cy.get('.svg-icon').click()
  })
  it('Auth_ERROR', () => {
    cy.visit('https://dabrostyle.com/')
    cy.get('.svg-profile').click()
    cy.wait(2000)
    cy.get('#ec-login-email-input').type('Tester')
    cy.wait(2000)
    cy.get('#ec-login-password-input').type('Test')
    cy.wait(2000)
    cy.get('.svg-icon').click()
  })
  it('Order', () => {
    cy.visit('https://dabrostyle.com/')
    cy.wait(2000)
    cy.get('.grid-category--id-133250304 > .grid-category__wrap > .grid-category__wrap-inner > .grid-category__card > .grid-category__image > .grid-category__shadow').click()
    cy.wait(2000)
    cy.get('.grid-product--id-342677067 > .grid-product__wrap > .grid-product__wrap-inner > .grid-product__image > .grid-product__image-wrap > .grid-product__picture').click()
    cy.wait(2000)
    cy.get('.details-product-purchase__add-buttons > .form-control--primary > .form-control__button').click()
    cy.wait(2000)
    cy.get('.ec-cart-widget').click()
    cy.wait(2000)
    cy.get('#form-control__checkbox--agree').click()
    cy.wait(2000)
    cy.get('#ec-cart-email-input').type('Tester@mail.ru')
    cy.wait(2000)
    cy.get('.form-control__button > .form-control__loader').click()
    cy.wait(2000)
    cy.get('#ec-full-name').type('Иванов Иван Иванович')
    cy.wait(2000)
    cy.get('#ec-phone').type('+71234567890')
    cy.wait(2000)
    cy.get('.ec-tabs__wrap > [tabindex="0"]').click()
    cy.wait(2000)
    cy.get('.form-control__loader').click()
  })
  it('Order_ERROR', () => {
    cy.visit('https://dabrostyle.com/')
    cy.wait(2000)
    cy.get('.grid-category--id-133250304 > .grid-category__wrap > .grid-category__wrap-inner > .grid-category__card > .grid-category__image > .grid-category__shadow').click()
    cy.wait(2000)
    cy.get('.grid-product--id-342677067 > .grid-product__wrap > .grid-product__wrap-inner > .grid-product__image > .grid-product__image-wrap > .grid-product__picture').click()
    cy.wait(2000)
    cy.get('.details-product-purchase__add-buttons > .form-control--primary > .form-control__button').click()
    cy.wait(2000)
    cy.get('.ec-cart-widget').click()
    cy.wait(2000)
    cy.get('#form-control__checkbox--agree').click()
    cy.wait(2000)
    cy.get('#ec-cart-email-input').type('Tester')
    cy.wait(2000)
    cy.get('.form-control__button > .form-control__loader').click()
  })
  it('favorites', () => {
    cy.visit('https://dabrostyle.com/')
    cy.wait(2000)
    cy.get('.grid-category--id-133250304 > .grid-category__wrap > .grid-category__wrap-inner > .grid-category__card > .grid-category__image > .grid-category__shadow').click()
    cy.wait(2000)
    cy.get('.grid-product--id-342677067 > .grid-product__wrap > .grid-product__wrap-inner > .grid-product__image > .grid-product__image-wrap > .grid-product__picture').click()
    cy.wait(2000)
    cy.get('.favorite-product__button-add > .form-control__button').click()
    cy.wait(2000)
    cy.get('.favorite-product__button-view > .form-control__button').click()
    cy.wait(2000)
    cy.get('.favorite-product__button-add > .form-control__button').click()
  })
  it('Change__password', () => {
    cy.visit('https://dabrostyle.com/')
    cy.wait(2000)
    cy.get('.svg-profile').click()
    cy.wait(2000)
    cy.get('.ec-cart__checkout > .ec-page-links > .ec-page-links__wrapper > :nth-child(1) > .ec-link').click()
    cy.wait(2000)
    cy.get('#ec-reset-password-email-input').type("Tester@mail.ru")
    cy.wait(2000)
    cy.get('.form-control__loader').click()
  })
})