describe('template spec', () => {
  // it('passes', () => {
  //   cy.visit('https://dabrostyle.com/')
  //   cy.get('.svg-profile').click()
  //   cy.wait(2000)
  //   cy.get(':nth-child(2) > .ec-link').click()
  //   cy.wait(2000)
  //   cy.get('#ec-register-name-input').type("Test")
  //   cy.wait(2000)
  //   cy.get('#ec-register-email-input').type("test@mail.ru")
  //   cy.wait(2000)
  //   cy.get('#ec-register-password-input').type("test1337")
  //   cy.wait(2000)
  //   cy.get('.svg-icon').click()
  // })
  // it('passes', () => {
  //   cy.visit('https://dabrostyle.com/')
  //   cy.get('.svg-profile').click()
  //   cy.wait(2000)
  //   cy.get(':nth-child(2) > .ec-link').click()
  //   cy.wait(2000)
  //   cy.get('.ec-cart-step__change').click()
  //   cy.wait(2000)
  //   cy.get('#ec-login-email-input').type('Tester@mail.ru')
  //   cy.wait(2000)
  //   cy.get('#ec-login-password-input').type('Test1337')
  //   cy.wait(2000)
  //   cy.get('.svg-icon').click()
  // })
  it('passes', () => {
    cy.visit('https://dabrostyle.com/')
    cy.wait(2000)
    cy.get('.grid-category--id-133250304 > .grid-category__wrap > .grid-category__wrap-inner > .grid-category__card > .grid-category__image > .grid-category__shadow').click()
    cy.wait(2000)
    cy.get('.grid-product--id-342677067 > .grid-product__wrap > .grid-product__wrap-inner > .grid-product__image > .grid-product__image-wrap > .grid-product__picture').click()
    cy.wait(2000)
    cy.get('.details-product-purchase__add-buttons > .form-control--primary > .form-control__button').click()
    cy.wait(2000)
    cy.get('.ec-cart-widget').click()
  })
})